steps:
  - name: "gcr.io/cloud-builders/npm:latest"
    args: ['install']
  
  - name: "gcr.io/cloud-builders/npm:latest"
    entrypoint: npm 
    args: ['run', 'build']
 
  - name: 'gcr.io/sonarcloud/sonar-scanner'
    entrypoint: 'sonar-scanner'
    args:
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.login=${_SONAR_TOKEN}' # Set your SonarCloud token here


